### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by tgunr** [jeffreywildman/homebrew-virt-manager#133]
```
==> Patching
patching file virt-manager
Hunk #1 succeeded at 170 (offset 19 lines).
==> Downloading https://files.pythonhosted.org/packages/a9/8a/580c7176f01540615c2eb3f3ab5462613b4beac4aa63410be89ecc7b7472/
Already downloaded: /Users/davec/Library/Caches/Homebrew/downloads/93188db770e5a2cc745d843c379ae7f650e2198f127a55a5aa3758689f60b5c4--virtualenv-16.7.2.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/virt-manager--homebrew-virtualenv-20190801-
==> python3 -s /private/tmp/virt-manager--homebrew-virtualenv-20190801-20077-fgxsfr/target/bin/virtualenv -p python3 /usr/l
==> Downloading https://libvirt.org/sources/python/libvirt-python-5.5.0.tar.gz
Already downloaded: /Users/davec/Library/Caches/Homebrew/downloads/628543437a876e2c7b392a37f9c9c46461e85851c2d1287fca91198fdd7e9cf5--libvirt-python-5.5.0.tar.gz
==> /usr/local/Cellar/virt-manager/2.2.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private
Last 15 lines from /Users/davec/Library/Logs/Homebrew/virt-manager/03.pip:
Removed build tracker '/private/tmp/pip-req-tracker-carqocmd'
ERROR: Command errored out with exit status 1: /usr/local/Cellar/virt-manager/2.2.1/libexec/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-req-build-ty4ygh54/setup.py'"'"'; __file__='"'"'/private/tmp/pip-req-build-ty4ygh54/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-rkrprbzf/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/2.2.1/libexec/bin/../include/site/python3.7/libvirt-python Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.2.1/libexec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/virt-manager/2.2.1/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 407, in run
    use_user_site=options.use_user_site,
  File "/usr/local/Cellar/virt-manager/2.2.1/libexec/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/usr/local/Cellar/virt-manager/2.2.1/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 959, in install
    spinner=spinner,
  File "/usr/local/Cellar/virt-manager/2.2.1/libexec/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 934, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/local/Cellar/virt-manager/2.2.1/libexec/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-req-build-ty4ygh54/setup.py'"'"'; __file__='"'"'/private/tmp/pip-req-build-ty4ygh54/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-rkrprbzf/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/2.2.1/libexec/bin/../include/site/python3.7/libvirt-python Check the logs for full command output.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
osx virt-manager console screen is black https://github.com/jeffreywildman/homebrew-virt-manager/issues/113
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62
```

**Comment by jeffreywildman** [comment]
Perhaps an issue with your python environment? `brew install -vd virt-manager` may help.

**Comment by J-Siu** [comment]
Got exact same issue when upgradeing:

```
$ brew upgrade virt-manager
==> Upgrading 1 outdated package:
jeffreywildman/virt-manager/virt-manager 2.2.1 -> 2.2.1_1
==> Upgrading jeffreywildman/virt-manager/virt-manager 
==> Downloading https://virt-manager.org/download/sources/virt-manager/virt-manager-2.2.1.tar.gz
Already downloaded: /Users/js/Library/Caches/Homebrew/downloads/77e22463a35b2e2bde8d02253c10129aabb1e5dfbfe2e6f33ef87bd35955dcf2--virt-manager-2.2.1.tar.gz
==> Patching
patching file virt-manager
Hunk #1 succeeded at 170 (offset 19 lines).
==> Downloading https://files.pythonhosted.org/packages/11/74/2c151a13ef41ab9fb43b3c4ff9e788e0496ed7923b2078d42cab30622bdf/virtualenv-16.7.4.tar.gz
Already downloaded: /Users/js/Library/Caches/Homebrew/downloads/507d2087bf24df82641b681a5fe4da778ef50ebe819a86ea1b584f70788f0f63--virtualenv-16.7.4.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/virt-manager--homebrew-virtualenv-20190904-15483-12y1k42/target --install-scripts=/private/tmp/virt-manager--homebrew-virtualenv-20190904-15483-12y1k42/target/bin --single-version-externally-managed --record=installed.txt
==> python3 -s /private/tmp/virt-manager--homebrew-virtualenv-20190904-15483-12y1k42/target/bin/virtualenv -p python3 /usr/local/Cellar/virt-manager/2.2.1_1/libexec
==> Downloading https://libvirt.org/sources/python/libvirt-python-5.6.0.tar.gz
Already downloaded: /Users/js/Library/Caches/Homebrew/downloads/def643dad17080fab38cb736c865c4fc4bcce0a91ecc639de720a629b5e714cf--libvirt-python-5.6.0.tar.gz
==> /usr/local/Cellar/virt-manager/2.2.1_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/virt-manager--libvirt-python-20190904-15483-1vp3k96/libvirt-python-5.6.0
Last 15 lines from /Users/js/Library/Logs/Homebrew/virt-manager/03.pip:
Removed build tracker '/private/tmp/pip-req-tracker-zkugth4i'
ERROR: Command errored out with exit status 1: /usr/local/Cellar/virt-manager/2.2.1_1/libexec/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-req-build-b057_w2l/setup.py'"'"'; __file__='"'"'/private/tmp/pip-req-build-b057_w2l/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-k2ocvvak/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/2.2.1_1/libexec/bin/../include/site/python3.7/libvirt-python Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.2.1_1/libexec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/virt-manager/2.2.1_1/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 407, in run
    use_user_site=options.use_user_site,
  File "/usr/local/Cellar/virt-manager/2.2.1_1/libexec/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/usr/local/Cellar/virt-manager/2.2.1_1/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 959, in install
    spinner=spinner,
  File "/usr/local/Cellar/virt-manager/2.2.1_1/libexec/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 931, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/local/Cellar/virt-manager/2.2.1_1/libexec/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-req-build-b057_w2l/setup.py'"'"'; __file__='"'"'/private/tmp/pip-req-build-b057_w2l/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-k2ocvvak/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/2.2.1_1/libexec/bin/../include/site/python3.7/libvirt-python Check the logs for full command output.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
(virt-manager:75950): GSpice-CRITICAL **: 13:08:42.543: send_key: assertion 'scancode != 0' failed https://github.com/jeffreywildman/homebrew-virt-manager/issues/135
osx virt-manager console screen is black https://github.com/jeffreywildman/homebrew-virt-manager/issues/113
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62
```

**Comment by J-Siu** [comment]
I tried with: brew install -vd virt-manager
Log attached.
[virt-manager.zip](https://github.com/jeffreywildman/homebrew-virt-manager/files/3575419/virt-manager.zip)

**Comment by techana** [comment]
I got exactly the same error while running `brew install virt-manager virt-viewer`

```
 ==> /usr/local/Cellar/virt-manager/2.2.1_1/libexec/bin/pip install -v --no-deps 
Last 15 lines from /Users/mans/Library/Logs/Homebrew/virt-manager/03.pip:
Removed build tracker '/private/tmp/pip-req-tracker-_66yfgpr'
ERROR: Command errored out with exit status 1: /usr/local/Cellar/virt-manager/2.2.1_1/libexec/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-req-build-7i_4tejt/setup.py'"'"'; __file__='"'"'/private/tmp/pip-req-build-7i_4tejt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-j97i_gyp/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/2.2.1_1/libexec/bin/../include/site/python3.7/libvirt-python Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.2.1_1/libexec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/virt-manager/2.2.1_1/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 407, in run
    use_user_site=options.use_user_site,
  File "/usr/local/Cellar/virt-manager/2.2.1_1/libexec/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/usr/local/Cellar/virt-manager/2.2.1_1/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 959, in install
    spinner=spinner,
  File "/usr/local/Cellar/virt-manager/2.2.1_1/libexec/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 931, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/local/Cellar/virt-manager/2.2.1_1/libexec/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-req-build-7i_4tejt/setup.py'"'"'; __file__='"'"'/private/tmp/pip-req-build-7i_4tejt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-j97i_gyp/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/2.2.1_1/libexec/bin/../include/site/python3.7/libvirt-python Check the logs for full command output.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
(virt-manager:75950): GSpice-CRITICAL **: 13:08:42.543: send_key: assertion 'scancode != 0' failed https://github.com/jeffreywildman/homebrew-virt-manager/issues/135
osx virt-manager console screen is black https://github.com/jeffreywildman/homebrew-virt-manager/issues/113
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62
```

**Comment by samagnew** [comment]
Also if upgrading an existing installation..

$ brew upgrade virt-manager
==> Upgrading 1 outdated package:
jeffreywildman/virt-manager/virt-manager 1.4.1 -> 2.2.1_1
==> Upgrading jeffreywildman/virt-manager/virt-manager 
==> Downloading https://virt-manager.org/download/sources/virt-manager/virt-manager-2.2.1.tar.gz
Already downloaded: /Users/saa2012/Library/Caches/Homebrew/downloads/77e22463a35b2e2bde8d02253c10129aabb1e5dfbfe2e6f33ef87bd35955dcf2--virt-manager-2.2.1.tar.gz
==> Patching
patching file virt-manager
Hunk #1 succeeded at 170 (offset 19 lines).
==> Downloading https://files.pythonhosted.org/packages/11/74/2c151a13ef41ab9fb43b3c4ff9e788e0496ed7923b2078d42cab30622bdf/virtualenv-16.7.4.tar.gz
Already downloaded: /Users/saa2012/Library/Caches/Homebrew/downloads/507d2087bf24df82641b681a5fe4da778ef50ebe819a86ea1b584f70788f0f63--virtualenv-16.7.4.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/virt-manager--homebrew-virtualenv-20190905-39254-4jlux8/target --install-scripts=/private/tmp/virt-manager--homebrew-virtualenv-20190905-39254-4jlux8/target/bin --single-version-externally-managed --record=installed.txt
==> python3 -s /private/tmp/virt-manager--homebrew-virtualenv-20190905-39254-4jlux8/target/bin/virtualenv -p python3 /usr/local/Cellar/virt-manager/2.2.1_1/libexec
==> Downloading https://libvirt.org/sources/python/libvirt-python-5.6.0.tar.gz
Already downloaded: /Users/saa2012/Library/Caches/Homebrew/downloads/def643dad17080fab38cb736c865c4fc4bcce0a91ecc639de720a629b5e714cf--libvirt-python-5.6.0.tar.gz
==> /usr/local/Cellar/virt-manager/2.2.1_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/virt-manager--libvirt-python-20190905-39254-ptbks8/libvirt-python-5.6.0
Last 15 lines from /Users/saa2012/Library/Logs/Homebrew/virt-manager/03.pip:
Removed build tracker '/private/tmp/pip-req-tracker-v6b7ss68'
ERROR: Command errored out with exit status 1: /usr/local/Cellar/virt-manager/2.2.1_1/libexec/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-req-build-cdeyaudj/setup.py'"'"'; __file__='"'"'/private/tmp/pip-req-build-cdeyaudj/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-8jebxw23/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/2.2.1_1/libexec/bin/../include/site/python3.7/libvirt-python Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.2.1_1/libexec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/virt-manager/2.2.1_1/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 407, in run
    use_user_site=options.use_user_site,
  File "/usr/local/Cellar/virt-manager/2.2.1_1/libexec/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/usr/local/Cellar/virt-manager/2.2.1_1/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 959, in install
    spinner=spinner,
  File "/usr/local/Cellar/virt-manager/2.2.1_1/libexec/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 931, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/local/Cellar/virt-manager/2.2.1_1/libexec/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-req-build-cdeyaudj/setup.py'"'"'; __file__='"'"'/private/tmp/pip-req-build-cdeyaudj/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-8jebxw23/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/2.2.1_1/libexec/bin/../include/site/python3.7/libvirt-python Check the logs for full command output.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
(virt-manager:75950): GSpice-CRITICAL **: 13:08:42.543: send_key: assertion 'scancode != 0' failed https://github.com/jeffreywildman/homebrew-virt-manager/issues/135
osx virt-manager console screen is black https://github.com/jeffreywildman/homebrew-virt-manager/issues/113
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62

**Comment by J-Siu** [comment]
@techana virt-viewer will install by itself. The issue is only for virt-manager.

**Comment by J-Siu** [comment]
The issue is pip/pip3 failed to install libvirt-python-5.6.0.

It actually show in the output:
```

### Download from https://...

==> Downloading https://libvirt.org/sources/python/libvirt-python-5.6.0.tar.gz
Already downloaded: /Users/saa2012/Library/Caches/Homebrew/downloads/def643dad17080fab38cb736c865c4fc4bcce0a91ecc639de720a629b5e714cf--libvirt-python-5.6.0.tar.gz

### pip install using the download file

==> /usr/local/Cellar/virt-manager/2.2.1_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/virt-manager--libvirt-python-20190905-39254-ptbks8/libvirt-python-5.6.0
```

I download libvirt-python-5.6.0.tar.gz to a folder and follow the command manually:

```
─$ pip3 install -v --no-deps --no-binary :all: --ignore-installed libvirt-python-5.6.0.tar.gz                                                                                                                                                                                                        1 ↵
Created temporary directory: /private/var/folders/y1/jr7gnyzs39g878wm3xtf3rr00000gn/T/pip-ephem-wheel-cache-aw_up99t
Created temporary directory: /private/var/folders/y1/jr7gnyzs39g878wm3xtf3rr00000gn/T/pip-req-tracker-wuu5q5af
Created requirements tracker '/private/var/folders/y1/jr7gnyzs39g878wm3xtf3rr00000gn/T/pip-req-tracker-wuu5q5af'
Created temporary directory: /private/var/folders/y1/jr7gnyzs39g878wm3xtf3rr00000gn/T/pip-install-eqz6ln2s
Processing ./libvirt-python-5.6.0.tar.gz
  Created temporary directory: /private/var/folders/y1/jr7gnyzs39g878wm3xtf3rr00000gn/T/pip-req-build-tpdw9iux
  Added file:///Users/js/Downloads/libvirt-python-5.6.0.tar.gz to build tracker '/private/var/folders/y1/jr7gnyzs39g878wm3xtf3rr00000gn/T/pip-req-tracker-wuu5q5af'
    Running setup.py (path:/private/var/folders/y1/jr7gnyzs39g878wm3xtf3rr00000gn/T/pip-req-build-tpdw9iux/setup.py) egg_info for package from file:///Users/js/Downloads/libvirt-python-5.6.0.tar.gz
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/libvirt_python.egg-info
    writing pip-egg-info/libvirt_python.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/libvirt_python.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/libvirt_python.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/libvirt_python.egg-info/SOURCES.txt'
    file build/libvirt.py (for module libvirt) not found
    file build/libvirt_qemu.py (for module libvirt_qemu) not found
    file build/libvirt_lxc.py (for module libvirt_lxc) not found
    file build/libvirtaio.py (for module libvirtaio) not found
    reading manifest file 'pip-egg-info/libvirt_python.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/libvirt_python.egg-info/SOURCES.txt'
  Source in /private/var/folders/y1/jr7gnyzs39g878wm3xtf3rr00000gn/T/pip-req-build-tpdw9iux has version 5.6.0, which satisfies requirement libvirt-python==5.6.0 from file:///Users/js/Downloads/libvirt-python-5.6.0.tar.gz
  Removed libvirt-python==5.6.0 from file:///Users/js/Downloads/libvirt-python-5.6.0.tar.gz from build tracker '/private/var/folders/y1/jr7gnyzs39g878wm3xtf3rr00000gn/T/pip-req-tracker-wuu5q5af'
Skipping bdist_wheel for libvirt-python, due to binaries being disabled for it.
Installing collected packages: libvirt-python
  Created temporary directory: /private/var/folders/y1/jr7gnyzs39g878wm3xtf3rr00000gn/T/pip-record-_7cqxd4f
    Running command /usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/y1/jr7gnyzs39g878wm3xtf3rr00000gn/T/pip-req-build-tpdw9iux/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/y1/jr7gnyzs39g878wm3xtf3rr00000gn/T/pip-record-_7cqxd4f/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    /usr/local/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
    /usr/local/opt/python/bin/python3.7 generator.py libvirt /usr/local/Cellar/libvirt/5.7.0/share/libvirt/api/libvirt-api.xml
    Found 474 functions in /usr/local/Cellar/libvirt/5.7.0/share/libvirt/api/libvirt-api.xml
    Found 0 functions in libvirt-override-api.xml
    Generated 384 wrapper functions
    Missing type converters:
    virTypedParameterPtr *:1
    ERROR: failed virDomainGetGuestInfo
    error: command '/usr/local/opt/python/bin/python3.7' failed with exit status 1
  Running setup.py install for libvirt-python ... error
Cleaning up...
  Removing source in /private/var/folders/y1/jr7gnyzs39g878wm3xtf3rr00000gn/T/pip-req-build-tpdw9iux
Removed build tracker '/private/var/folders/y1/jr7gnyzs39g878wm3xtf3rr00000gn/T/pip-req-tracker-wuu5q5af'
ERROR: Command "/usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/y1/jr7gnyzs39g878wm3xtf3rr00000gn/T/pip-req-build-tpdw9iux/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/y1/jr7gnyzs39g878wm3xtf3rr00000gn/T/pip-record-_7cqxd4f/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/y1/jr7gnyzs39g878wm3xtf3rr00000gn/T/pip-req-build-tpdw9iux/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 951, in install
    spinner=spinner,
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/y1/jr7gnyzs39g878wm3xtf3rr00000gn/T/pip-req-build-tpdw9iux/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/y1/jr7gnyzs39g878wm3xtf3rr00000gn/T/pip-record-_7cqxd4f/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/y1/jr7gnyzs39g878wm3xtf3rr00000gn/T/pip-req-build-tpdw9iux/
```

I think one possibility is libvirt is 5.7.0 now. But virt-manager is still pulling 5.6.0 libvirt-python.

**Comment by jeffreywildman** [comment]
@J-Siu Thanks, you've got it right. This is related to #91. Fixed with 9069bac84c2abd530e903098421bdbec97484944.

**Comment by MichelDiz** [comment]
Still not working, I'm not able to do the same solution as J-Siu shared.

> That was my first start. I never used KVM in MacOS before. And an error right away.

error like:
```
Removed build tracker '/private/var/folders/x1/bz12z9ms4b7cx46yzptgb2fr0000gn/T/pip-req-tracker-4eqwg29f'
ERROR: Command "/usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/x1/bz12z9ms4b7cx46yzptgb2fr0000gn/T/pip-req-build-kvedm1fl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/x1/bz12z9ms4b7cx46yzptgb2fr0000gn/T/pip-record-77vz1w9q/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/x1/bz12z9ms4b7cx46yzptgb2fr0000gn/T/pip-req-build-kvedm1fl/
```

and  the original error

```
brew install virt-manager virt-viewer                                                     
==> Installing virt-manager from jeffreywildman/virt-manager
(...)
==> /usr/local/Cellar/virt-manager/2.2.1_2/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/virt-manager--libvi
Last 15 lines from /Users/micheldiznvme/Library/Logs/Homebrew/virt-manager/03.pip:
Removed build tracker '/private/tmp/pip-req-tracker-kgveg6m8'
ERROR: Command errored out with exit status 1: /usr/local/Cellar/virt-manager/2.2.1_2/libexec/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-req-build-55_zmo7d/setup.py'"'"'; __file__='"'"'/private/tmp/pip-req-build-55_zmo7d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-x7qa54xq/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/2.2.1_2/libexec/bin/../include/site/python3.7/libvirt-python Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 407, in run
    use_user_site=options.use_user_site,
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 959, in install
    spinner=spinner,
  File "/usr/local/Cellar/virt-manager/2.2.1_2/libexec/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 931, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/local/Cellar/virt-manager/2.2.1_2/libexec/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-req-build-55_zmo7d/setup.py'"'"'; __file__='"'"'/private/tmp/pip-req-build-55_zmo7d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-x7qa54xq/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/virt-manager/2.2.1_2/libexec/bin/../include/site/python3.7/libvirt-python Check the logs for full command output.

```
